-- Supabase PostgreSQL Schema for InfraKB

-- ── TYPES ──────────────────────────────────────────────────
CREATE TYPE user_role AS ENUM ('ADMIN', 'EDITOR', 'VIEWER');
CREATE TYPE doc_status AS ENUM ('DRAFT', 'PUBLISHED', 'PUBLIC', 'ARCHIVED');

-- ── PROFILES (Extends Supabase Auth) ────────────────────────
CREATE TABLE IF NOT EXISTS public.profiles (
  id           UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email        TEXT UNIQUE NOT NULL,
  username     TEXT UNIQUE NOT NULL,
  display_name TEXT NOT NULL,
  role         user_role DEFAULT 'EDITOR',
  avatar_url   TEXT,
  is_active    BOOLEAN DEFAULT TRUE,
  last_login_at TIMESTAMPTZ,
  created_at   TIMESTAMPTZ DEFAULT NOW(),
  updated_at   TIMESTAMPTZ DEFAULT NOW()
);

-- ── CATEGORIES ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.categories (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         TEXT UNIQUE NOT NULL,
  slug         TEXT UNIQUE NOT NULL,
  icon         TEXT,
  description  TEXT,
  parent_id    BIGINT REFERENCES public.categories(id),
  sort_order   INT DEFAULT 0,
  created_at   TIMESTAMPTZ DEFAULT NOW()
);

-- ── DOCUMENTS ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.documents (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title        TEXT NOT NULL,
  slug         TEXT UNIQUE NOT NULL,
  content      TEXT NOT NULL,
  excerpt      TEXT,
  category_id  BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,
  author_id    UUID REFERENCES public.profiles(id) NOT NULL,
  os_env       TEXT,
  status       doc_status DEFAULT 'PUBLISHED',
  is_pinned    BOOLEAN DEFAULT FALSE,
  view_count   INT DEFAULT 0,
  created_at   TIMESTAMPTZ DEFAULT NOW(),
  updated_at   TIMESTAMPTZ DEFAULT NOW(),
  published_at TIMESTAMPTZ
);

-- ── TAGS ───────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.tags (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         TEXT UNIQUE NOT NULL,
  slug         TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS public.doc_tags (
  doc_id       BIGINT REFERENCES public.documents(id) ON DELETE CASCADE,
  tag_id       BIGINT REFERENCES public.tags(id) ON DELETE CASCADE,
  PRIMARY KEY (doc_id, tag_id)
);

-- ── DOCUMENT VERSIONS ──────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.doc_versions (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  doc_id       BIGINT REFERENCES public.documents(id) ON DELETE CASCADE,
  content      TEXT NOT NULL,
  title        TEXT NOT NULL,
  edited_by    UUID REFERENCES public.profiles(id),
  change_summary TEXT,
  created_at   TIMESTAMPTZ DEFAULT NOW()
);

-- ── ATTACHMENTS ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.attachments (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  doc_id       BIGINT REFERENCES public.documents(id) ON DELETE CASCADE,
  filename     TEXT NOT NULL,
  stored_name  TEXT NOT NULL,
  mime_type    TEXT NOT NULL,
  size_bytes   BIGINT NOT NULL,
  url          TEXT NOT NULL,
  uploaded_by  UUID REFERENCES public.profiles(id),
  created_at   TIMESTAMPTZ DEFAULT NOW()
);

-- ── ACTIVITY LOG ───────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.activity_logs (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id      UUID REFERENCES public.profiles(id),
  doc_id       BIGINT REFERENCES public.documents(id) ON DELETE SET NULL,
  action       TEXT NOT NULL,
  meta         JSONB,
  ip_address   TEXT,
  created_at   TIMESTAMPTZ DEFAULT NOW()
);

-- ── FULL TEXT SEARCH INDEX ────────────────────────────────
-- PostgreSql Full Text Search
ALTER TABLE public.documents ADD COLUMN fts tsvector GENERATED ALWAYS AS (
  to_tsvector('english', title || ' ' || coalesce(content, ''))
) STORED;

CREATE INDEX documents_fts_idx ON public.documents USING GIN (fts);

-- ── RPC FUNCTIONS ─────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.increment_view_count(doc_id BIGINT)
RETURNS void AS $$
BEGIN
  UPDATE public.documents
  SET view_count = view_count + 1
  WHERE id = doc_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.delete_document(target_doc_id BIGINT)
RETURNS void AS $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM public.documents 
    WHERE id = target_doc_id AND (author_id = auth.uid() OR public.is_admin())
  ) THEN
    DELETE FROM public.documents WHERE id = target_doc_id;
  ELSE
    RAISE EXCEPTION 'Unauthorized to delete this document';
  END IF;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ── AUTOMATIC VERSIONING TRIGGER ──────────────────────────
CREATE OR REPLACE FUNCTION public.handle_document_version()
RETURNS TRIGGER AS $$
BEGIN
  IF (TG_OP = 'UPDATE') THEN
    INSERT INTO public.doc_versions (doc_id, content, title, edited_by)
    VALUES (OLD.id, OLD.content, OLD.title, OLD.author_id);
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER on_document_update
  BEFORE UPDATE ON public.documents
  FOR EACH ROW EXECUTE FUNCTION public.handle_document_version();

-- ── ROW LEVEL SECURITY (RLS) ──────────────────────────────
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.doc_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.doc_versions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attachments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.activity_logs ENABLE ROW LEVEL SECURITY;

-- Basic Policies (Public access to published docs if authenticated)
CREATE POLICY "Authenticated users can view published docs" ON public.documents
  FOR SELECT USING (auth.role() = 'authenticated' AND status IN ('PUBLISHED', 'PUBLIC'));

CREATE POLICY "Anyone can view PUBLIC docs" ON public.documents
  FOR SELECT USING (status = 'PUBLIC');

CREATE POLICY "Users can insert own documents" ON public.documents
  FOR INSERT WITH CHECK (auth.uid() = author_id);

CREATE POLICY "Users can update own documents" ON public.documents
  FOR UPDATE USING (auth.uid() = author_id);

CREATE POLICY "Users can delete own documents" ON public.documents
  FOR DELETE USING (auth.uid() = author_id);

-- Child table cascading delete policies
CREATE POLICY "Users can delete own doc_versions" ON public.doc_versions
  FOR DELETE USING (EXISTS (SELECT 1 FROM public.documents WHERE id = doc_id AND author_id = auth.uid()));

CREATE POLICY "Users can delete own doc_tags" ON public.doc_tags
  FOR DELETE USING (EXISTS (SELECT 1 FROM public.documents WHERE id = doc_id AND author_id = auth.uid()));

CREATE POLICY "Users can delete own attachments" ON public.attachments
  FOR DELETE USING (EXISTS (SELECT 1 FROM public.documents WHERE id = doc_id AND author_id = auth.uid()));

CREATE POLICY "Users can view all categories" ON public.categories
  FOR SELECT USING (auth.role() = 'authenticated');

-- More complex RBAC policies would be added here based on 'profiles.role'

-- ── PROFILE POLICIES & HELPER FUNCTIONS ───────────────────
-- Helper function to check admin status without triggering infinite recursion on profiles table
CREATE OR REPLACE FUNCTION public.is_admin() 
RETURNS boolean AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.profiles 
    WHERE id = auth.uid() AND role = 'ADMIN'
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Users can view their own profile
CREATE POLICY "Users can view own profile" 
ON public.profiles 
FOR SELECT 
TO authenticated 
USING (auth.uid() = id);

-- Users can update their own profile
CREATE POLICY "Users can update own profile" 
ON public.profiles 
FOR UPDATE 
TO authenticated 
USING (auth.uid() = id);

-- Admins can view all profiles
CREATE POLICY "Admins can view all profiles" 
ON public.profiles 
FOR SELECT 
TO authenticated 
USING (public.is_admin());

-- ── AUTH TRIGGER ──────────────────────────────────────────
-- Function to automatically create a profile when a new user signs up via Supabase Auth
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
DECLARE
  is_first_user BOOLEAN;
  base_name TEXT;
BEGIN
  -- 1. Check if this is the first user in the system to grant ADMIN role
  SELECT (NOT EXISTS (SELECT 1 FROM public.profiles LIMIT 1)) INTO is_first_user;

  -- 2. Extract base name from email
  base_name := split_part(NEW.email, '@', 1);

  -- 3. Insert into profiles
  INSERT INTO public.profiles (
    id, 
    email, 
    username, 
    display_name, 
    role,
    is_active
  )
  VALUES (
    NEW.id,
    NEW.email,
    -- Unique username: base_name + random number
    base_name || '_' || floor(random() * 9999 + 1000)::text,
    -- Display Name: metadata or base_name
    COALESCE(NEW.raw_user_meta_data->>'displayName', base_name),
    -- First user is ADMIN, others are VIEWER
    CASE WHEN is_first_user THEN 'ADMIN'::public.user_role ELSE 'VIEWER'::public.user_role END,
    TRUE
  );

  RETURN NEW;
EXCEPTION WHEN OTHERS THEN
  -- Fallback to ensure user creation doesn't fail even if profile sync has an issue
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Re-create the trigger
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

