-- Supabase PostgreSQL Schema for InfraKB

-- ── TYPES ──────────────────────────────────────────────────
CREATE TYPE user_role AS ENUM ('ADMIN', 'EDITOR', 'VIEWER');
CREATE TYPE doc_status AS ENUM ('DRAFT', 'PUBLISHED', 'PUBLIC', 'ARCHIVED');

-- ── PROFILES (Extends Supabase Auth) ────────────────────────
CREATE TABLE IF NOT EXISTS public.profiles (
  id           UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email        TEXT UNIQUE NOT NULL,
  username     TEXT UNIQUE NOT NULL,
  display_name TEXT NOT NULL,
  role         user_role DEFAULT 'EDITOR',
  avatar_url   TEXT,
  is_active    BOOLEAN DEFAULT TRUE,
  last_login_at TIMESTAMPTZ,
  created_at   TIMESTAMPTZ DEFAULT NOW(),
  updated_at   TIMESTAMPTZ DEFAULT NOW()
);

-- ── CATEGORIES ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.categories (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         TEXT UNIQUE NOT NULL,
  slug         TEXT UNIQUE NOT NULL,
  icon         TEXT,
  description  TEXT,
  parent_id    BIGINT REFERENCES public.categories(id),
  sort_order   INT DEFAULT 0,
  created_at   TIMESTAMPTZ DEFAULT NOW()
);

-- ── DOCUMENTS ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.documents (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title        TEXT NOT NULL,
  slug         TEXT UNIQUE NOT NULL,
  content      TEXT NOT NULL,
  excerpt      TEXT,
  category_id  BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,
  author_id    UUID REFERENCES public.profiles(id) NOT NULL,
  os_env       TEXT,
  status       doc_status DEFAULT 'PUBLISHED',
  is_pinned    BOOLEAN DEFAULT FALSE,
  view_count   INT DEFAULT 0,
  created_at   TIMESTAMPTZ DEFAULT NOW(),
  updated_at   TIMESTAMPTZ DEFAULT NOW(),
  published_at TIMESTAMPTZ
);

-- ── TAGS ───────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.tags (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         TEXT UNIQUE NOT NULL,
  slug         TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS public.doc_tags (
  doc_id       BIGINT REFERENCES public.documents(id) ON DELETE CASCADE,
  tag_id       BIGINT REFERENCES public.tags(id) ON DELETE CASCADE,
  PRIMARY KEY (doc_id, tag_id)
);

-- ── DOCUMENT VERSIONS ──────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.doc_versions (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  doc_id       BIGINT REFERENCES public.documents(id) ON DELETE CASCADE,
  content      TEXT NOT NULL,
  title        TEXT NOT NULL,
  edited_by    UUID REFERENCES public.profiles(id),
  change_summary TEXT,
  created_at   TIMESTAMPTZ DEFAULT NOW()
);

-- ── ATTACHMENTS ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.attachments (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  doc_id       BIGINT REFERENCES public.documents(id) ON DELETE CASCADE,
  filename     TEXT NOT NULL,
  stored_name  TEXT NOT NULL,
  mime_type    TEXT NOT NULL,
  size_bytes   BIGINT NOT NULL,
  url          TEXT NOT NULL,
  uploaded_by  UUID REFERENCES public.profiles(id),
  created_at   TIMESTAMPTZ DEFAULT NOW()
);

-- ── ACTIVITY LOG ───────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.activity_logs (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id      UUID REFERENCES public.profiles(id),
  doc_id       BIGINT REFERENCES public.documents(id) ON DELETE SET NULL,
  action       TEXT NOT NULL,
  meta         JSONB,
  ip_address   TEXT,
  created_at   TIMESTAMPTZ DEFAULT NOW()
);

-- ── FULL TEXT SEARCH INDEX ────────────────────────────────
-- PostgreSql Full Text Search
ALTER TABLE public.documents ADD COLUMN fts tsvector GENERATED ALWAYS AS (
  to_tsvector('english', title || ' ' || coalesce(content, ''))
) STORED;

CREATE INDEX documents_fts_idx ON public.documents USING GIN (fts);

-- ── AUTOMATIC VERSIONING TRIGGER ──────────────────────────
CREATE OR REPLACE FUNCTION public.handle_document_version()
RETURNS TRIGGER AS $$
BEGIN
  IF (TG_OP = 'UPDATE') THEN
    INSERT INTO public.doc_versions (doc_id, content, title, edited_by)
    VALUES (OLD.id, OLD.content, OLD.title, OLD.author_id);
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER on_document_update
  BEFORE UPDATE ON public.documents
  FOR EACH ROW EXECUTE FUNCTION public.handle_document_version();

-- ── ROW LEVEL SECURITY (RLS) ──────────────────────────────
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.doc_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.doc_versions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attachments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.activity_logs ENABLE ROW LEVEL SECURITY;

-- Basic Policies (Public access to published docs if authenticated)
CREATE POLICY "Authenticated users can view published docs" ON public.documents
  FOR SELECT USING (auth.role() = 'authenticated' AND status IN ('PUBLISHED', 'PUBLIC'));

CREATE POLICY "Anyone can view PUBLIC docs" ON public.documents
  FOR SELECT USING (status = 'PUBLIC');

CREATE POLICY "Users can view all categories" ON public.categories
  FOR SELECT USING (auth.role() = 'authenticated');

-- More complex RBAC policies would be added here based on 'profiles.role'
